### ISSUE TITLE
Problems compiling mate-file-manager on 10.0-ALPHA2

### ISSUE THREAD

**Issue by StayFrosty** [jlmess77/mate-ports#2]
mate-file-manager is failing to build on 10.0-ALPHA2.  The configure script is failing while doing the C compiler sanity check.  It's failing using LLVM/Clang and GCC 4.9 built from ports.  Here's the output:

checking for style of include used by gmake... GNU
checking for gcc... gcc49
checking whether the C compiler works... no
configure: error: in `/usr/ports/x11-fm/mate-file-manager/work/mate-file-manager-1.6.1':
configure: error: C compiler cannot create executables

**Comment by StayFrosty** [comment]
I suppose I should also add that I have verified both Clang and GCC are indeed working by building other ports, etc...

**Comment by mmoll** [comment]
@StayFrosty look into config.log what's the actual error triggered by this test.

**Comment by StayFrosty** [comment]
configure:3634: checking for C compiler version
configure:3643: cc --version >&5
FreeBSD clang version 3.3 (tags/RELEASE_33/final 183502) 20130610
Target: x86_64-unknown-freebsd10.0
Thread model: posix
configure:3654: $? = 0
configure:3643: cc -v >&5
FreeBSD clang version 3.3 (tags/RELEASE_33/final 183502) 20130610
Target: x86_64-unknown-freebsd10.0
Thread model: posix
configure:3654: $? = 0
configure:3643: cc -V >&5
cc: error: argument to '-V' is missing (expected 1 value)
cc: error: no input files
configure:3654: $? = 1
configure:3643: cc -qversion >&5
cc: error: no input files
configure:3654: $? = 1
configure:3674: checking whether the C compiler works
configure:3696: cc -O2 -pipe -fno-strict-aliasing -I/usr/local/include  conftest.c -pthread -L/usr/local/lib -liconv >&5
/usr/bin/ld: cannot find -liconv
cc: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3700: $? = 1
configure:3738: result: no

**Comment by mmoll** [comment]
@StayFrosty check the entry 20130904 in /usr/ports/UPDATING
I'm pretty sure, that's the reason.

**Comment by StayFrosty** [comment]
I don't have libiconv on my system.  Just for grins, I figured I'd double check.

root@PDC1055368:~ # pkg query %ro libiconv
root@PDC1055368:~ # pkg delete -f libiconv
Package(s) not found!

So it looks like I don't have libiconv or anything depending on it installed.

**Comment by mmoll** [comment]
OK, then libiconv should come from the base system, I don't have a FreeBSD 10 install at hand, but there should be a libiconv.so in /usr/lib then

**Comment by kwm81** [comment]
libiconv might not be install anymore via ports, but I hazzard a guess that there are still libraries that link to it old ports version.

**Comment by jlmess77** [comment]
The mate-file-manager's Makefile will need to be edited. Remove the
-L/usr/local/lib -liconv from the CONFIGURE_ENV= LIBS part.

On Mon, Sep 30, 2013 at 3:24 PM, Koop Mast notifications@github.com wrote:

> libiconv might not be install anymore via ports, but I hazzard a guess that
> there are still libraries that link to it old ports version.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

mezz.freebsd@gmail.com - mezz@FreeBSD.org
FreeBSD GNOME Team
http://www.FreeBSD.org/gnome/ - gnome@FreeBSD.org

**Comment by ericbsd** [comment]
That might be the case i still run under 9.2 and it work well for now. I
might be able to switch to 10 next
month.

On Mon, Sep 30, 2013 at 5:24 PM, Koop Mast notifications@github.com wrote:

> libiconv might not be install anymore via ports, but I hazzard a guess
> that there are still libraries that link to it old ports version.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jlmess77/mate-ports/issues/2#issuecomment-25402414
> .

## 

_Eric Turgeon
*_GhostBSD project*
Office location:
1-11 connaught
Moncton NB Canada
www.ghostbsd.org http://www.ghostbsd.org/

**Comment by kwm81** [comment]
please let me know if it broken, it might need ${ICONV_LIBS}

**Comment by StayFrosty** [comment]
Still failing for me. 

configure:3674: checking whether the C compiler works
configure:3696: cc -O2 -pipe -fno-strict-aliasing -I/usr/local/include  conftest.c -pthread -L/usr/local/lib -liconv >&5
/usr/bin/ld: cannot find -liconv
cc: error: linker command failed with exit code 1 (use -v to see invocation)

Here's what's in my Makefile:
root@PDC1055368:/usr/ports/x11-fm/mate-file-manager # cat Makefile | grep CONFIGURE_ENV
CONFIGURE_ENV=  LIBS="${PTHREAD_LIBS} -L${LOCALBASE}/lib -liconv" \

**Comment by StayFrosty** [comment]
@kwm81 Looks like it's still happening.

**Comment by StayFrosty** [comment]
Never mind, for some reason matemerge.sh wasn't updating the MATE ports and was merging the old tree.  I updated manually and it's working .  Thanks.

**Comment by ericbsd** [comment]
Look like solve
