### ISSUE TITLE
gnome-keyring installed by mate

### ISSUE THREAD

**Issue by pkgdemon** [jlmess77/mate-ports#3]
I've been noticing that the gnome 2 version of gnome-keyring is getting installed by mate.  I do not see this when installing x11/mate-base.

I checked the source for x11/mate-screensaver and said that it was set to use mate-keying.  Then i checked bsd.mate.mk just to see if it might somehow be referenced there and everything looked ok.

When i do pkg delete gnome-keyring because it was installed when i installed mate it says gnome-keyring is required by mate-screensaver, xscreensaver-hacks, and mate

**Comment by pkgdemon** [comment]
After further investigation x11/mate-screensaver built x11/xscreensaver-gnome-hacks.  x11/xscreensaver-gnome-hacks is part of FreeBSD ports tree.  x11/xscreensaver-gnome-hacks is what is building and installing gnome-keyring.

**Comment by pkgdemon** [comment]
This shows up during the configure of xscreensaver-gnome-hacks.  

xscreensaver-gnome-hacks-5.12_1 depends on file: /usr/local/lib/pam_gnome_keyring.so - not found

**Comment by pkgdemon** [comment]
The x11/xscreensaver-gnome-hacks port seems to be a slave port for x11/xscreensaver-gnome which is told to build security/gnome-keyring.

**Comment by jlmess77** [comment]
In the MATE 1.8, they have replaced libmatekeyring and mate-keyring with libsecret and gnome-keyring. It means that the libmatekeyring and mate-keyring will be removed. I don't have much of time and I have asked FreeBSD core/portmgr to hold my commit bit in the attic until I return. However, I will remind that to kwm and ericbsd. It looks like ericbsd is working on MATE mostly? I am not sure but I will ask kwm about it.

**Comment by kwm81** [comment]
I was working on 1.7.90 when I asked eric to look at two mate ports. Then MATE 1.8 release popped up and I think eric decided to do the whole thing. not that I mind I got enough on my mind. And I did see the axe ports list.

**Comment by ericbsd** [comment]
Jeremy don't worry about
 time for MATE I will try to put some time on it.

On Fri, Mar 14, 2014 at 12:58 PM, Koop Mast notifications@github.comwrote:

> I was working on 1.7.90 when I asked eric to look at two mate ports. Then
> MATE 1.8 release popped up and I think eric decided to do the whole thing.
> not that I mind I got enough on my mind. And I did see the axe ports list.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/jlmess77/mate-ports/issues/3#issuecomment-37664056
> .

## 

_Eric Turgeon__GhostBSD project_
Office location:
1-11 connaught
Moncton NB Canada
www.ghostbsd.org http://www.ghostbsd.org/

**Comment by pkgdemon** [comment]
Old issue.  Closing.
