### ISSUE TITLE
Cant compile latest mate port

### ISSUE THREAD

**Issue by ghost** [jlmess77/mate-ports#9]
Hi!
I am trying to build your mate port using your instructions and matemerge.sh script from github. But at the end of compilation I receive the following errors (retyped from screen, because I cant copy+paste from tty) :

===>  Applying FreeBSD patches for mate-contols-center-1.8.1
Ignoring previously applied (or reversed) patch.
3 out of 3 hunks ignored--saving rejects to configure.reg
=. Patch patch-configure failed to apply cleanly.
=> Patch(es) pathc-capplets-common_mate-theme-info.c applied cleanely.
**\* Error code 1

Stop.
Make[2]: stopped in /usr/ports/sysutils/mate-contol-center
**\* Error code 1

Stop.
Make[1]: stopped in /usr/ports/x11/mate-base
**\* Error code 1

Stop.
Make: stopped in /usr/ports/x11/mate

I hope you can help me :) I dont want to use any other DE (currently I am linux mint + mate user). Sorry for bad english sometimes.

Best wishes, Xdevelnet.

P.S. I also write an email for you, but it seems like you didnt check your mailbox on freebsd.org server.

**Comment by ericbsd** [comment]
This patch need to be fix first, then you will be able to install, until someone fix that patch no one will be able to install fully MATE before that fix.

**Comment by kwm81** [comment]
mate-control-center should be fixed now, mind you that I haven't checked all ports yet after the update, so there might still be more ports that don't build yet.

**Comment by ghost** [comment]
Thank you!
One more question: Is it possible to skip compilation of this port? I am using pure Xorg with TWM, and its a little bit hard to call it "desktop" :)
